routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;

//La ruta admin, contiene todas las rutas cuyos métodos son propios de el controlador admin
//la directiva de can es un directiva que permite conocer el rol de un usuario, como middleware, un usuario no puede manualmente
//acceder a las rutas de los administradores.
Route::middleware('can:admin')->group(function(){

    Route::get('', [HomeController::class, 'index'])->name('admin.home');

    // Solo necesito acceder a las tres rutas
    Route::resource('users', UserController::class)->only(['index','edit','update'])->names('admin.users');
    
    Route::resource('categories', CategoryController::class)->names('admin.categories');
    
    Route::resource('tags', TagController::class)->names('admin.tags');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('language');

Route::get('/', [App\Http\Controllers\BlogController::class,'index'])->middleware('language');
Route::get('/blog', [App\Http\Controllers\BlogController::class,'index'])->name('blog');
Route::get('/search', [App\Http\Controllers\BlogController::class,'search'])->name('search');
Route::get('/category/{category}', [App\Http\Controllers\BlogController::class,'category'])->name('category');
Route::get('/tag/{tag}', [App\Http\Controllers\BlogController::class,'tag'])->name('tag');
Route::get('/showPost/{post}', [App\Http\Controllers\BlogController::class,'showPost'])->name('showPost');

Auth::routes(['verify' => 'true']);

//Para poder editar, precisas del rol editor, y estar verificado
Route::middleware(['auth' => 'verified', 'language', 'can:editor'])->controller(App\Http\Controllers\BlogController::class)->group(function(){
    Route::get('/create', 'create')->name('create');
    Route::post('posts','store')->name('store');
    Route::get('/showUserPosts/{name}', 'showUserPosts')->name('showUserPosts');
    Route::get('/showPost/{post}/edit', 'edit')->name('edit');
    Route::put('/blog/{post}', 'update')->name('update');
    Route::delete('/post/{post}', 'destroy')->name('destroy');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
  use HasFactory;
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name','slug'];

    //Cambia la clave, la usualmente utilizada de la ruta(id) por la propiedad slug
    public function getRouteKeyName()
    {
      return "slug";
    }


    public function posts()
    {
        return $this->hasMany('App\Models\Post', 'category_id', 'id');
    }
    

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->merge(['slug' => Str::slug($request->input('name'))]);

        $request->validate([
            // Le especifico la tabla donde quiero que sea unico
            'name' => "required|unique:categories",
            'slug' => "required|unique:categories",
        ]);

        $category = Category::create($request->all());
        return redirect()->route('admin.categories.edit', $category)->with('info', 'The category has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->merge(['slug' => Str::slug($request->input('name'))]);

        $request->validate([
            // Le especifico la tabla donde quiero que sea unico
            'name' => "required|unique:categories,name,$category->id",
            'slug' => "required|unique:categories,slug,$category->id",
        ]);

        $category->update($request->all());
        return redirect()->route('admin.categories.edit', $category)->with('info', 'Category was successfully edited');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('admin.categories.index')->with('info', 'The category has been succesfully deleted');
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')


@section('content_header')
    <h1>Create categories</h1>
@stop

{{-- Laravel collective form --}}
@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::open(['route' => 'admin.categories.store']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Category name']) !!}

                @error('name')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            {!! Form::submit('Create category', ['class' => 'btn btn-success']) !!}

            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')


@section('content_header')
    <h1>Edit categories</h1>
@stop

@section('content')

    @if (session('info'))
        <div class="alert alert-success">
            <strong>{{session('info')}}</strong>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            {{-- De esta manera, cargamos la categoria que previamente creamos, para que laravel collection cree los calores de ese registro  --}}
            {!! Form::model($category, ['route' => ['admin.categories.update', $category], 'method' => 'put']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Category name']) !!}

                @error('name')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            {!! Form::submit('Edit category', ['class' => 'btn btn-warning']) !!}

            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>List of categories</h1>
@stop

@section('content')

    @if (session('info'))
        <div class="alert alert-danger">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif


    <div class="card">
        <div class="card-header">
            <a class="btn btn-success bn-sm" href="{{ route('admin.categories.create') }}">Create category</a>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Name
                        </th>
                        <th colspan="2">

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td>{{ $category->name }}</td>
                            <td width="10px">
                                <a href="{{ route('admin.categories.edit', $category) }}"
                                    class="btn btn-warning btn-sm">Edit</a>
                            </td>
                            <td width="10px">
                                <form action="{{ route('admin.categories.destroy', $category) }}" method="POST">
                                    @csrf
                                    @method('delete')

                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')


@section('content_header')
    <h1>One category</h1>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@endsection

@section('js')
    <script></script>
@endsection