routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\UserController;

//La ruta admin, contiene todas las rutas cuyos métodos son propios de el controlador admin
//la directiva de can es un directiva que permite conocer el rol de un usuario, como middleware, un usuario no puede manualmente
//acceder a las rutas de los administradores.
Route::middleware('can:admin')->group(function(){

    Route::get('', [HomeController::class, 'index'])->name('admin.home');

    // Solo necesito acceder a las tres rutas
    Route::resource('users', UserController::class)->only(['index','edit','update'])->names('admin.users');
    
    Route::resource('categories', CategoryController::class)->names('admin.categories');
    
    Route::resource('tags', TagController::class)->names('admin.tags');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('language');

Route::get('/', [App\Http\Controllers\BlogController::class,'index'])->middleware('language');
Route::get('/blog', [App\Http\Controllers\BlogController::class,'index'])->name('blog');
Route::get('/search', [App\Http\Controllers\BlogController::class,'search'])->name('search');
Route::get('/category/{category}', [App\Http\Controllers\BlogController::class,'category'])->name('category');
Route::get('/tag/{tag}', [App\Http\Controllers\BlogController::class,'tag'])->name('tag');
Route::get('/showPost/{post}', [App\Http\Controllers\BlogController::class,'showPost'])->name('showPost');

Auth::routes(['verify' => 'true']);

//Para poder editar, precisas del rol editor, y estar verificado
Route::middleware(['auth' => 'verified', 'language', 'can:editor'])->controller(App\Http\Controllers\BlogController::class)->group(function(){
    Route::get('/create', 'create')->name('create');
    Route::post('posts','store')->name('store');
    Route::get('/showUserPosts/{name}', 'showUserPosts')->name('showUserPosts');
    Route::get('/showPost/{post}/edit', 'edit')->name('edit');
    Route::put('/blog/{post}', 'update')->name('update');
    Route::delete('/post/{post}', 'destroy')->name('destroy');
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $fillable = ['name','slug', 'color'];

    public function getRouteKeyName()
    {
      return "slug";
    }

    //RELACION MUCHOS A MUCHOS 

    public function posts(){
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Tag;
use Illuminate\Support\Str;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $colors = [
            'danger' => 'Red',
            'primary' => 'Blue',
            'success' => 'Green',
            'warning' => 'Yellow',
        ];

        return view('admin.tags.create', compact('colors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->merge(['slug' => Str::slug($request->input('name'))]);

        $request->validate([
            // Le especifico la tabla donde quiero que sea unico
            'name' => "required|unique:tags",
            'slug' => "required|unique:tags",
            'color' => "required"
        ]);

        $tag = Tag::create($request->all());
        return redirect()->route('admin.tags.edit', $tag)->with('info', 'The tag has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        

        return view('admin.tags.show', compact('tag'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        $colors = [
            'danger' => 'Red',
            'primary' => 'Blue',
            'success' => 'Green',
            'warning' => 'Yellow',
        ];

        return view('admin.tags.edit', compact('tag','colors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $request->merge(['slug' => Str::slug($request->input('name'))]);

        $request->validate([
            // Le especifico la tabla donde quiero que sea unico
            'name' => "required|unique:tags,name,$tag->id",
            'slug' => "required|unique:tags,slug,$tag->id",
            'color' => "required",
        ]);

        $tag->update($request->all());
        return redirect()->route('admin.tags.edit', $tag)->with('info', 'Tag was successfully edited');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect()->route('admin.tags.index')->with('info', 'Tag has been delete successfully');
    }
}

resources/views/admin/tags/create.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>Create tag</h1>
@stop

@section('content')

    @if (session('info'))
        <div class="alert alert-danger">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            {!! Form::open(['route' => 'admin.tags.store']) !!}
            @include('admin.tags.partials.form')
            {!! Form::submit('Create tag', ['class' => 'btn btn-success']) !!}

            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/admin/tags/edit.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>Edit tag</h1>
@stop

@section('content')

    @if (session('info'))
        <div class="alert alert-success">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif
    <div class="card">
        <div class="card-body">
            {{-- De esta manera, cargamos la categoria que previamente creamos, para que laravel collection cree los calores de ese registro  --}}
            {!! Form::model($tag, ['route' => ['admin.tags.update', $tag], 'method' => 'put']) !!}
            @include('admin.tags.partials.form')
            {!! Form::submit('Edit tag', ['class' => 'btn btn-warning']) !!}

            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/admin/tags/index.blade.php
@extends('adminlte::page')

@section('content_header')

    <a class="btn btn-success btn-sm float-right" href="{{route('admin.tags.create')}}">Create tag</a>
    <h1>List of tags</h1>
@stop

@section('content')

    @if (session('info'))
        <div class="alert alert-danger">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($tags as $tag)
                        <tr>
                            <td>{{ $tag->id }}</td>
                            <td>{{ $tag->name }}</td>
                            <td width="10px"> <a href="{{ route('admin.tags.edit', $tag) }}"
                                    class="btn btn-warning btn-sm">Edit</a></td>
                            <td width="10px">
                                <form action="{{ route('admin.tags.destroy', $tag) }}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/admin/tags/show.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>Show tag</h1>
@stop

@section('content')

    @if (session('info'))
        <div class="alert alert-danger">
            <strong>{{ session('info') }}</strong>
        </div>
    @endif


    <h1>Tags</h1>
@stop